name: hsound
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Core
  firebase_core: ^2.24.0
  
  # Firebase Authentication
  firebase_auth: ^4.17.1
  
  # Firebase Firestore
  cloud_firestore: ^4.13.0
  
  # Firebase Storage
  firebase_storage: ^11.5.3
  
  # Google Sign-In
  google_sign_in: ^6.1.1
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Image Picker
  image_picker: ^1.0.4
  
  # URL Launcher
  url_launcher: ^6.1.11
  
  # WebView
  webview_flutter: ^4.4.0
  
  # Cupertino Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logotipo_Hsound.png
    - assets/images/google_icon.png